# Site settings
title: crunchy_crow's blog
email: andriy.kogut@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hi, I'm Andriy Kohut and this is my blog.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://andriykohut.github.io/" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username: andriykohut

# Build settings
markdown: kramdown
